name: Checkout Private Repo via GitHub App

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checkout-private:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python (for JWT)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyJWT
        run: pip install PyJWT cryptography

      - name: Write GitHub App key
        run: |
          echo "${{ secrets.GH_APP_PRIVATE_KEY }}" > app.pem
          chmod 600 app.pem

      - name: Generate App JWT
        id: jwt
        run: |
          python - <<'PY'
          import os, time, jwt
          app_id = int(os.environ['GH_APP_ID'])
          with open("app.pem","rb") as f:
              key = f.read()
          now = int(time.time())
          payload = {"iat": now, "exp": now+540, "iss": app_id}
          token = jwt.encode(payload, key, algorithm="RS256")
          print(f"::add-mask::{token}")
          with open(os.environ["GITHUB_ENV"],"a") as fh:
              fh.write(f"APP_JWT={token}\n")
          PY
        env:
          GH_APP_ID: ${{ vars.GH_APP_ID }}

      - name: Exchange JWT for Installation Token
        id: token
        run: |
          echo "APP_JWT is set: $([ -n "$APP_JWT" ] && echo "YES" || echo "NO")"
          echo "Install ID: ${{ vars.GH_INSTALL_ID }}"
          
          resp=$(curl -s -X POST \
            -H "Authorization: Bearer $APP_JWT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/${{ vars.GH_INSTALL_ID }}/access_tokens)

          echo "Response: $resp"
          
          token=$(python -c "import sys,json; print(json.load(sys.stdin)['token'])" <<<"$resp")

          echo "::add-mask::$token"
          echo "INSTALL_TOKEN=$token" >> $GITHUB_ENV
        env:
          APP_JWT: ${{ env.APP_JWT }}

      - name: Checkout private repo 
        uses: actions/checkout@v4
        with:
          repository: Aidans-test-org/test-repo2-private
          token: ${{ env.INSTALL_TOKEN }}
          path: private-repo
          persist-credentials: false

      - name: List repo files
        run: ls -R private-repo
