name: Trigger Jenkins & Collect Artifacts

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        default: "main"
      jenkins_job_url:
        description: "Full Jenkins job URL"
        default: "https://cloud.wolfssl-test.com/jenkins/job/wolfProvider/job/debian-extraction"
        required: true
  push:
    branches: [ "main" ]   # optional auto-run on push to main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    outputs:
      build_tag: ${{ steps.set-tag.outputs.build_tag }}
    steps:
      - name: Trigger Jenkins build
        id: trigger
        run: |
          # Use input or fallback to hardcoded default
          JOB_URL="${{ github.event.inputs.jenkins_job_url || 'https://cloud.wolfssl-test.com/jenkins/job/wolfProvider/job/debian-extraction' }}"
          
          # Extract Jenkins base URL for auth test
          JENKINS_BASE=$(echo "$JOB_URL" | grep -oP 'https?://[^/]+')
          
          echo "Jenkins URL: $JENKINS_BASE"
          echo "Job URL: $JOB_URL"
          
          # Test authentication first
          echo "Testing Jenkins authentication..."
          AUTH_TEST=$(curl -s -o /dev/null -w "%{http_code}" \
            "$JENKINS_BASE/api/json" \
            --user "jenkins-bot:${{ secrets.WOLFSSL_BOT_TOKEN }}")
          echo "Auth test status: $AUTH_TEST"
          
          if [ "$AUTH_TEST" != "200" ]; then
            echo "ERROR: Authentication failed (status: $AUTH_TEST)"
            echo "Please verify:"
            echo "  1. Jenkins URL is correct: $JENKINS_BASE"
            echo "  2. Username 'jenkins-bot' exists"
            echo "  3. WOLFSSL_BOT_TOKEN is correct"
            exit 1
          fi

          # Build the trigger URL
          FULL_JOB_URL="${JOB_URL}/buildWithParameters"
          echo "Triggering: $FULL_JOB_URL"
          
          # Trigger Jenkins job and capture response
          RESPONSE=$(curl -s -X POST -i \
            "$FULL_JOB_URL?token=${{ secrets.WOLFSSL_BOT_TOKEN }}&branch=${{ github.event.inputs.branch }}" \
            --user "jenkins-bot:${{ secrets.WOLFSSL_BOT_TOKEN }}")
          
          # Extract Location header (don't print full response - may contain sensitive data)
          BUILD_URL=$(echo "$RESPONSE" | grep -i "^location:" | awk '{print $2}' | tr -d '\r')
          
          if [ -z "$BUILD_URL" ]; then
            echo "ERROR: Failed to get build URL from Jenkins"
            HTTP_STATUS=$(echo "$RESPONSE" | grep -i "^HTTP" | head -1)
            echo "HTTP Status: $HTTP_STATUS"
            exit 1
          fi
          
          echo "Jenkins job triggered successfully"
          echo "Waiting for Jenkins to queue job..."
          sleep 10

          # Poll until build finishes
          while true; do
            STATUS=$(curl -s "$BUILD_URL/api/json" --user "jenkins-bot:${{ secrets.WOLFSSL_BOT_TOKEN }}" | jq -r '.result')
            if [[ "$STATUS" == "SUCCESS" ]]; then
              echo "Jenkins build succeeded."
              break
            elif [[ "$STATUS" == "FAILURE" ]]; then
              echo "Jenkins build failed!"
              exit 1
            elif [[ "$STATUS" == "null" ]]; then
              echo "Build still running..."
              sleep 20
            else
              echo "Unknown status: $STATUS"
              sleep 10
            fi
          done

      - name: Determine Jenkins tag
        id: set-tag
        run: |
          BUILD_TAG="jenkins-artifacts-${GITHUB_RUN_ID}"
          echo "build_tag=$BUILD_TAG" >> $GITHUB_OUTPUT

      - name: Download artifacts from GitHub Release
        run: |
          TAG="${{ steps.set-tag.outputs.build_tag }}"
          echo "Downloading artifacts from release: $TAG"
          gh release download "$TAG" --repo wolfssl/wolfProvider --dir ./downloaded
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts for downstream jobs
        uses: actions/upload-artifact@v4
        with:
          name: jenkins-artifacts
          path: ./downloaded/*
