name: Trigger Private Workflow

on:
    workflow_dispatch:
    push:
      branches: [ 'main' ]
      # Only runs AFTER PR is merged by trusted maintainer
    # SECURITY NOTES:
    # - pull_request: SAFE - forks cannot access secrets
    # - pull_request_target: DANGEROUS - has access to secrets!
    # - push: SAFE if you review PRs before merging
    # - workflow_dispatch: SAFE - requires manual approval

permissions:
  contents: read

jobs:
  trigger-private:
    runs-on: ubuntu-latest
    steps:
      - name: Check repo access and workflows
        run: |
          echo "Checking repo access..."
          repo_response=$(curl -s \
            -H "Authorization: token ${{ secrets.PRIVATE_REPO_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Aidans-test-org/test-repo4-private-testing)
          
          echo "Repo response:"
          echo "$repo_response" | jq '.'
          
          echo ""
          echo "Checking available workflows..."
          workflows_response=$(curl -s \
            -H "Authorization: token ${{ secrets.PRIVATE_REPO_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Aidans-test-org/test-repo4-private-testing/actions/workflows)
          
          echo "Workflows response:"
          echo "$workflows_response" | jq '.'

      - name: Trigger workflow in private repo
        run: |
          workflow_file="clone-test-repo2-private.yml"
          
          curl -X POST \
            -H "Authorization: token ${{ secrets.PRIVATE_REPO_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Aidans-test-org/test-repo4-private-testing/actions/workflows/${workflow_file}/dispatches \
            -d '{"ref":"main"}'
