name: Checkout Private Repo

on:
  workflow_dispatch:

  push:
    paths:
      - .github/workflows/use-github-app.yml

jobs:
  checkout-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test-repo2-private
        uses: actions/checkout@v4
        with:
          repository: Aidan-test-org/test-repo2-private
